Fix 	CleanerThread and read/write test from kafka
bernd/samsa pull request #1
Opened 2016-10-15 06:41 UTC by fbalicchia

I play a little around samsa cause i like the idea. thanks if you want check my commit.
Any suggest are wellcome

2016-10-16 17:37 UTC, bernd requested changes

2016-10-16 17:37 UTC, bernd commented on pom.xml
> +            <version>0.8.2.1</version>
I guess these dependencies can be in `<scope>test</scope>` because they are only needed for the tests, right?

2016-10-16 17:37 UTC, bernd commented on pom.xml
> +            <version>0.13.0</version>
See above.

2016-10-16 17:37 UTC, bernd commented on pom.xml
> +            <version>2.9</version>
See above.

2016-10-24 04:15 UTC, fbalicchia commented on pom.xml
> +            <version>0.8.2.1</version>
Opss, Yes you are right

2016-11-09 07:34 UTC, closed without merging

2016-11-09 07:37 UTC, fbalicchia commented
Continue in spare time, as soon as I have something significant' I'll reopen request